-- The volumetric cloud march (phase_clouds_march): half-resolution, every direction, blended
-- with the previous frame. The noise volumes are generated by tools/gen_cloud_noise.py.

function normal (shader, t_base, t_second, t_detail)
	shader:begin	("da_fullscreen","da_clouds_march")
			: fog	(false)
			: zb 	(false,false)
			: blend	(false, blend.one, blend.zero)
	shader:dx10texture	("s_cloud_map",		"$user$cloud_map")
	shader:dx10texture	("s_clouds_hist",	"$user$clouds1")
	shader:dx10texture	("s_cloud_shape",	"da\\da_cloud_shape")
	shader:dx10texture	("s_cloud_detail",	"da\\da_cloud_detail")
	shader:dx10sampler	("smp_linear")
	shader:dx10sampler	("smp_rtlinear")
end
