local function on_init(menu)
	menu.gameplay_options["infinite_bolts"] = {typ="check"}
	menu.gameplay_options["pause_in_background"] = {typ="check"}
	menu.gameplay_options["crosshair_dot"] = {typ="check"}
end

local function on_set_values(menu, opt_manager)
	local console = get_console()
	local infinite_bolts = menu.gameplay_options["infinite_bolts"]
	if (infinite_bolts and infinite_bolts.ctrl) then
		infinite_bolts.ctrl:SetCheck(console:get_bool("g_infinite_bolts"))
	end

	local pause_in_background = menu.gameplay_options["pause_in_background"]
	if (pause_in_background and pause_in_background.ctrl) then
		pause_in_background.ctrl:SetCheck(console:get_bool("g_pause_in_background"))
	end

	local crosshair_dot = menu.gameplay_options["crosshair_dot"]
	if (crosshair_dot and crosshair_dot.ctrl) then
		crosshair_dot.ctrl:SetCheck(console:get_bool("hud_crosshair_dot"))
	end
end

local function on_accept(menu, opt_manager, console)
	local infinite_bolts = menu.gameplay_options["infinite_bolts"]
	if (infinite_bolts and infinite_bolts.ctrl) then
		console:execute("g_infinite_bolts " .. (infinite_bolts.ctrl:GetCheck() and "1" or "0"))
	end

	local pause_in_background = menu.gameplay_options["pause_in_background"]
	if (pause_in_background and pause_in_background.ctrl) then
		console:execute("g_pause_in_background " .. (pause_in_background.ctrl:GetCheck() and "1" or "0"))
	end

	local crosshair_dot = menu.gameplay_options["crosshair_dot"]
	if (crosshair_dot and crosshair_dot.ctrl) then
		console:execute("hud_crosshair_dot " .. (crosshair_dot.ctrl:GetCheck() and "1" or "0"))
	end
end

RegisterScriptCallback("opt_menu_on_init", on_init)
RegisterScriptCallback("opt_menu_on_set_values", on_set_values)
RegisterScriptCallback("opt_menu_on_accept", on_accept)
