# Reproduce a bug report on the rig from the save the reporter attached.
#
#   tools\qa\Run-ReportRepro.ps1 -Report 20260911T072213.980993309Z-788e8c0ebf9f5d06 -Label skybox
#
# A diagnostic zip carries the save group the player was in when they wrote the report, so the
# scene the report is about can be stood in rather than guessed at. The save is unpacked into the
# rig under the report's label, the freshly built engine loads it, and one frame comes back next
# to the log. Nothing of the player's own install is touched; the rig is a clone.
[CmdletBinding()]
param(
    # Folder name under $Inbox, or a full path to one.
    [Parameter(Mandatory)][string]$Report,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9_.-]+$')][string]$Label,
    [string]$Inbox = "D:\Games\BugReports",
    [string]$Rig = "D:\Games\Dead Air\_qa\lightdiag",
    [string]$Out = "D:\Games\Dead Air\DeadAir-x64\_work\report-repro",
    # Seconds to stand in the scene before the frame is taken.
    [int]$Settle = 12,
    # Frames around the horizon; 0 shoots only what the save was facing. Two more (up, down)
    # always follow.
    [int]$Views = 4,
    # Approach mode: instead of turning, walk this many metres forward between frames.
    [float]$Step = 0,
    # Name of a Lua global to call once, just before the first frame.
    [string]$Call = "",
    # Console commands issued BEFORE the save loads - a weather, a pinned wind seed, a renderer
    # knob. Whatever has to be in force at the level's first tick goes here.
    [string[]]$PreCommands = @(),
    [switch]$SkipDeploy,
    # A stale shader cache keeps the old shader after a source change, which reads as "my edit
    # did nothing".
    [switch]$KeepShaderCache
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")).Path

$reportDir = if (Test-Path -LiteralPath $Report) { (Resolve-Path -LiteralPath $Report).Path }
             else { Join-Path $Inbox $Report }
if (-not (Test-Path -LiteralPath $reportDir)) { throw "no report at $reportDir" }
$zip = Join-Path $reportDir "diagnostic.zip"
if (-not (Test-Path -LiteralPath $zip)) { throw "no diagnostic.zip in $reportDir - this report came without one" }

Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [IO.Compression.ZipFile]::OpenRead($zip)
try {
    $saves = Join-Path $Rig "appdata\savedgames"
    $taken = @()
    foreach ($ext in "scop", "scoc", "scov") {
        $entry = $archive.Entries | Where-Object { $_.Name -eq "save.$ext" } | Select-Object -First 1
        if (-not $entry) { continue }
        $dest = Join-Path $saves "$Label.$ext"
        [IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $dest, $true)
        $taken += "$Label.$ext"
    }
    if ($taken -notcontains "$Label.scop") { throw "the zip has no save group in it" }
    Write-Host "== unpacked $($taken -join ', ')"
}
finally { $archive.Dispose() }

# The engine's own shader payload, which is where our .ps/.h edits live. Without this the rig
# keeps whatever it was last given and a shader change reads as "my edit did nothing" - it did,
# on a copy nobody ran.
$pack = Join-Path $repo "packaging\dead-air-x64\compatibility\gamedata"
Copy-Item (Join-Path $pack "shaders/r3/*") (Join-Path $Rig "gamedata/shaders/r3/") -Force
Copy-Item (Join-Path $pack "configs/*.ltx") (Join-Path $Rig "gamedata/configs/") -Force -ErrorAction SilentlyContinue
Copy-Item (Join-Path $pack "scripts/*.script") (Join-Path $Rig "gamedata/scripts/") -Force -ErrorAction SilentlyContinue

if (-not $KeepShaderCache) {
    foreach ($name in "shaders_cache_xfr", "shaders_cache_oxr") {
        $cache = Join-Path $Rig "appdata\$name"
        if (Test-Path -LiteralPath $cache) { Remove-Item -LiteralPath $cache -Recurse -Force }
    }
}

# The engine names its own screenshot file and ignores the argument, so the only way to know
# which one is ours is that no others are left.
$shots = Join-Path $Rig "appdata\screenshots"
New-Item -ItemType Directory -Force -Path $shots | Out-Null
Get-ChildItem $shots -Filter "*.jpg" -ErrorAction SilentlyContinue | Remove-Item -Force

# Other QA scenarios tick alongside and would be in the frame.
$parked = @()
$scriptDir = Join-Path $Rig "gamedata\scripts"
foreach ($other in (Get-ChildItem $scriptDir -Filter "qa_*.script" -ErrorAction SilentlyContinue)) {
    if ($other.Name -eq "qa_repro.script") { continue }
    $off = "$($other.FullName).parked"
    Move-Item -LiteralPath $other.FullName -Destination $off -Force
    $parked += ,@($off, $other.FullName)
}

$lua = Join-Path $PSScriptRoot "repro\qa_repro.lua"
if (-not (Test-Path -LiteralPath $lua)) { throw "no scenario at $lua" }
Set-Content -LiteralPath (Join-Path $scriptDir "qa_repro.script") `
    -Value ("-- generated by Run-ReportRepro.ps1 - edit tools\qa\repro\qa_repro.lua, not this copy`n" +
            "qa_repro_settle = $Settle`nqa_repro_views = $Views`nqa_repro_step = $Step`nqa_repro_call = '$Call'`n" + [IO.File]::ReadAllText($lua)) -Encoding UTF8

try {
    & (Join-Path $PSScriptRoot "Run-ContentProbe.ps1") -Rig $Rig -Label "repro-$Label" `
        -RunSeconds ($Settle + 90 + $Views * 3) -TimeoutSeconds ($Settle + 200 + $Views * 3) -WaitFor "REPRO: DONE" `
        -ExtraArgs "-always_active" `
        -Commands ($PreCommands + @("start server($Label/single/alife/load) client(localhost)")) | Out-Null
}
finally {
    foreach ($pair in $parked) { Move-Item -LiteralPath $pair[0] -Destination $pair[1] -Force }
}

$dest = Join-Path $Out $Label
New-Item -ItemType Directory -Force -Path $dest | Out-Null
Get-ChildItem $dest -File -ErrorAction SilentlyContinue | Remove-Item -Force
$i = 0
Get-ChildItem $shots -Filter "*.jpg" | Sort-Object LastWriteTime | ForEach-Object {
    Copy-Item $_.FullName (Join-Path $dest ("{0:d2}.jpg" -f $i)) -Force
    $i++
}
Copy-Item (Join-Path $Rig "appdata\logs\xfined-ray_admin.log") (Join-Path $dest "log.txt") -Force

Write-Host "== repro $Label : $i frame(s) -> $dest"
$log = Join-Path $dest "log.txt"
if (Select-String -Path $log -Pattern "FATAL" -Quiet) { Write-Host "  !! FATAL in the log" }
Select-String -Path $log -Pattern "\[repro\]" | ForEach-Object { "  " + $_.Line }
