# One water QA pass on the rig: pin a weather, load a save, run a scenario script, collect the
# frames and the log under a named folder so two passes can be laid side by side.
#
#   tools\qa\Run-WaterQa.ps1 -Name surface-storm -Scenario surface -Save fogqa -Weather af3_bright_storm
#
# Scenarios live in tools\qa\water\<name>.lua and are copied to the rig as qa_water.script. They
# talk to the engine through the qa_water_* console commands and end by printing the marker the
# probe waits for, so a run costs as long as the scenario takes and not a fixed ceiling.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Name,
    [string]$Scenario = "surface",
    [string]$Save = "fogqa",
    [string]$Weather = "af3_bright_clear_4",
    [string]$Rig = "D:\Games\Dead Air\_qa\lightdiag",
    [string]$Out = "D:\Games\Dead Air\_work\water-rework-20260909\shots",
    [int]$Seconds = 120,
    # A stale shader cache keeps the old shader after a source change, which reads as "my edit did
    # nothing". Off only when timing a warm start on purpose.
    [switch]$KeepShaderCache
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")).Path
$lua = Join-Path $PSScriptRoot "water\$Scenario.lua"
if (-not (Test-Path -LiteralPath $lua)) { throw "no scenario at $lua" }

# The scenario reads its weather out of a global the header sets, so one file covers every cycle.
$header = "-- generated by Run-WaterQa.ps1 - edit tools\qa\water\$Scenario.lua, not this copy`nqa_water_weather = `"$Weather`"`n"
Set-Content -LiteralPath (Join-Path $Rig "gamedata\scripts\qa_water.script") `
    -Value ($header + [IO.File]::ReadAllText($lua)) -Encoding UTF8

$pack = Join-Path $repo "packaging\dead-air-x64\compatibility\gamedata"
Copy-Item (Join-Path $pack "shaders\r3\*") (Join-Path $Rig "gamedata\shaders\r3\") -Force
Copy-Item (Join-Path $pack "configs\*.ltx") (Join-Path $Rig "gamedata\configs\") -Force

$shots = Join-Path $Rig "appdata\screenshots"
Get-ChildItem $shots -Filter *.jpg -ErrorAction SilentlyContinue | Remove-Item -Force
if (-not $KeepShaderCache) {
    $cache = Join-Path $Rig "appdata\shaders_cache_oxr"
    if (Test-Path -LiteralPath $cache) { Remove-Item -LiteralPath $cache -Recurse -Force }
}

& (Join-Path $PSScriptRoot "Run-ContentProbe.ps1") -Rig $Rig -Label $Name -RunSeconds $Seconds `
    -TimeoutSeconds ($Seconds + 140) -WaitFor "DA_WATER_PROBE_DONE" `
    -Commands @("start server($Save/single/alife/load) client(localhost)") | Out-Null

$dest = Join-Path $Out $Name
New-Item -ItemType Directory -Force -Path $dest | Out-Null
Get-ChildItem $dest -File -ErrorAction SilentlyContinue | Remove-Item -Force
$i = 0
Get-ChildItem $shots -Filter *.jpg | Sort-Object LastWriteTime | ForEach-Object {
    Copy-Item $_.FullName (Join-Path $dest ("{0:d2}.jpg" -f $i)) -Force
    $i++
}
Copy-Item (Join-Path $Rig "appdata\logs\openxray_admin.log") (Join-Path $dest "log.txt") -Force

Write-Output "$Name : $i frame(s) -> $dest"
$log = Join-Path $dest "log.txt"
if (Select-String -Path $log -Pattern "FATAL" -Quiet) { Write-Output "  !! FATAL in the log" }
Select-String -Path $log -Pattern "\[qa\]" | ForEach-Object { "  " + $_.Line }
