# Sample the game thread on the rig and write the attribution next to the benchmark results.
#
#   tools\qa\optimization\Run-Profile.ps1 -Label escape -Seconds 25
#
# Runs with -always_active, because an engine that is not the foreground window throttles its
# frame loop and a profile taken through that throttle measures the throttle. Other QA
# scenarios are parked for the duration so nothing but the game is in the sample.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Label,
    [string]$Rig = "D:\Games\Dead Air\_qa\lightdiag",
    [string]$Save = "admin - quicksave6",
    [int]$Seconds = 20,
    [int]$Hz = 1000,
    [int]$Top = 45,
    # Symbols to ask "who called this?" about once the run is over, comma separated.
    # A single string on purpose: an array argument here unrolls into the positional
    # parameters behind it and quietly rewrites $Rig.
    [string]$Callers = "",
    [switch]$SkipDeploy
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..\..")).Path
$lua = Join-Path $PSScriptRoot "qa_profile.lua"
if (-not (Test-Path -LiteralPath $lua)) { throw "no scenario at $lua" }

if (-not $SkipDeploy) {
    $src = Join-Path $repo "bin\x64\Release"
    foreach ($f in (Get-Content -LiteralPath (Join-Path $repo "packaging\dead-air-x64\installer\runtime-files.txt"))) {
        if ($f -and (Test-Path -LiteralPath (Join-Path $src $f))) {
            Copy-Item (Join-Path $src $f) (Join-Path $Rig $f) -Force
        }
    }
    # The symbols are what turns addresses into names; without them the report is hex.
    Get-ChildItem $src -Filter *.pdb -ErrorAction SilentlyContinue |
        ForEach-Object { Copy-Item $_.FullName (Join-Path $Rig $_.Name) -Force }
}

# A stale shot from the last run reads as this run's frame; clear it before the game starts.
# The engine names its own file (ss_<user>_<date>_(<level>).jpg) and ignores the argument,
# so the only way to know which one is ours is that no others are left.
$shots = Join-Path $Rig "appdata\screenshots"
Get-ChildItem $shots -Filter "*.jpg" -ErrorAction SilentlyContinue | Remove-Item -Force

$parked = @()
$scriptDir = Join-Path $Rig "gamedata\scripts"
foreach ($other in (Get-ChildItem $scriptDir -Filter "qa_*.script" -ErrorAction SilentlyContinue)) {
    if ($other.Name -eq "qa_profile.script") { continue }
    $off = "$($other.FullName).parked"
    Move-Item -LiteralPath $other.FullName -Destination $off -Force
    $parked += ,@($off, $other.FullName)
}

$header = "-- generated by Run-Profile.ps1 - edit tools\qa\optimization\qa_profile.lua, not this copy`n" +
          "qa_profile_seconds = $Seconds`nqa_profile_hz = $Hz`nqa_profile_top = $Top`n" +
          "qa_profile_callers = { " +
          ((($Callers -split ",") | Where-Object { $_.Trim() } |
            ForEach-Object { '"' + $_.Trim() + '"' }) -join ", ") + " }`n"
Set-Content -LiteralPath (Join-Path $scriptDir "qa_profile.script") `
    -Value ($header + [IO.File]::ReadAllText($lua)) -Encoding UTF8

try {
    & (Join-Path $repo "tools\qa\Run-ContentProbe.ps1") -Rig $Rig -Label "profile-$Label" `
        -RunSeconds ($Seconds + 90) -TimeoutSeconds ($Seconds + 200) -WaitFor "PROFILE: DONE" `
        -ExtraArgs "-always_active" `
        -Commands @("start server($Save/single/alife/load) client(localhost)") | Out-Null
}
finally {
    foreach ($pair in $parked) { Move-Item -LiteralPath $pair[0] -Destination $pair[1] -Force }
}

$log = Join-Path $Rig "appdata\logs\xfined-ray_admin.log"
$resultRoot = Join-Path $PSScriptRoot "profiles"
New-Item -ItemType Directory -Force -Path $resultRoot | Out-Null
$dest = Join-Path $resultRoot "$Label.txt"

$lines = Select-String -Path $log -Pattern "\[profiler\]|PROFILE:" | ForEach-Object { $_.Line.Trim() }
if (-not $lines) { throw "no profiler output in $log - did the level load?" }
Set-Content -LiteralPath $dest -Value $lines -Encoding UTF8

$shot = Get-ChildItem $shots -Filter "*.jpg" -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime | Select-Object -Last 1
if ($shot) {
    $shotDest = Join-Path $resultRoot "$Label.jpg"
    Copy-Item $shot.FullName $shotDest -Force
}

Write-Host "== profile $Label =="
$lines | ForEach-Object { Write-Host "   $_" }
Write-Host "   -> $dest"
if ($shot) { Write-Host "   -> $(Join-Path $resultRoot "$Label.jpg")" }
