# One optimization benchmark pass on the rig (docs/dead-air/OPTIMIZATION_PLAN.md).
#
#   tools\qa\optimization\Run-OptBench.ps1 -Label baseline
#
# Deploys the freshly built runtime to the rig, loads a save, and lets qa_optbench.script
# run the engine's dar_bench_* commands once the level is up. Collects the [optbench] lines
# into results\<Label>.txt so two passes can be laid side by side - the timings say whether a
# change helped, and the workload invariants printed next to them (hit counts, summed ranges,
# expanded nodes, path length) say whether it changed an answer it had no business changing.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Label,
    [string]$Rig = "D:\Games\Dead Air\_qa\lightdiag",
    [string]$Save = "admin - quicksave6",
    [int]$Rays = 20000,
    [int]$Paths = 200,
    # Frame sampling needs an active window; the hidden-desktop probe throttles when
    # unfocused, so this is off unless a run asks for it.
    [int]$Frames = 0,
    [int]$Seconds = 240,
    [switch]$SkipDeploy
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..\..")).Path
$lua = Join-Path $PSScriptRoot "qa_optbench.lua"
if (-not (Test-Path -LiteralPath $lua)) { throw "no scenario at $lua" }

if (-not $SkipDeploy) {
    $src = Join-Path $repo "bin\x64\Release"
    $manifest = Join-Path $repo "packaging\dead-air-x64\installer\runtime-files.txt"
    foreach ($f in (Get-Content -LiteralPath $manifest)) {
        if ($f -and (Test-Path -LiteralPath (Join-Path $src $f))) {
            Copy-Item (Join-Path $src $f) (Join-Path $Rig $f) -Force
        }
    }
}

# Any other QA scenario left on the rig by an earlier run would tick alongside this one and
# land in the frame-time sample. Park them for the duration and put them back afterwards.
$parked = @()
$scriptDir = Join-Path $Rig "gamedata\scripts"
foreach ($other in (Get-ChildItem $scriptDir -Filter "qa_*.script" -ErrorAction SilentlyContinue)) {
    if ($other.Name -eq "qa_optbench.script") { continue }
    $off = "$($other.FullName).parked"
    Move-Item -LiteralPath $other.FullName -Destination $off -Force
    $parked += ,@($off, $other.FullName)
}

# The workload sizes reach the scenario as globals, so one file covers every size.
$header = "-- generated by Run-OptBench.ps1 - edit tools\qa\optimization\qa_optbench.lua, not this copy`n" +
          "qa_optbench_rays = $Rays`nqa_optbench_paths = $Paths`nqa_optbench_frames = $Frames`n"
Set-Content -LiteralPath (Join-Path $Rig "gamedata\scripts\qa_optbench.script") `
    -Value ($header + [IO.File]::ReadAllText($lua)) -Encoding UTF8

& (Join-Path $repo "tools\qa\Run-ContentProbe.ps1") -Rig $Rig -Label "optbench-$Label" -RunSeconds $Seconds `
    -TimeoutSeconds ($Seconds + 140) -WaitFor "OPTBENCH: DONE" `
    -Commands @("start server($Save/single/alife/load) client(localhost)") | Out-Null

foreach ($pair in $parked) { Move-Item -LiteralPath $pair[0] -Destination $pair[1] -Force }

$log = Join-Path $Rig "appdata\logs\xfined-ray_admin.log"
$resultRoot = Join-Path $PSScriptRoot "results"
New-Item -ItemType Directory -Force -Path $resultRoot | Out-Null
$dest = Join-Path $resultRoot "$Label.txt"

$lines = Select-String -Path $log -Pattern "\[optbench\]|OPTBENCH:" | ForEach-Object { $_.Line.Trim() }
if (-not $lines) { throw "no benchmark output in $log - did the level load?" }
Set-Content -LiteralPath $dest -Value $lines -Encoding UTF8

Write-Host "== optbench $Label =="
$lines | ForEach-Object { Write-Host "   $_" }
Write-Host "   -> $dest"
